#include "AssocPrec.h"
#include "../lex/Token.h"

const AssocPrec g_assoc_prec[TOK_NUM] = {
    [TOK_EOF]           = { RIGHT_ASSOCIATIVE, END_PRECEDENCE },
    [';']               = { RIGHT_ASSOCIATIVE, END_PRECEDENCE },
    [')']               = { RIGHT_ASSOCIATIVE, END_PRECEDENCE },
    ['}']               = { RIGHT_ASSOCIATIVE, END_PRECEDENCE },
    [']']               = { RIGHT_ASSOCIATIVE, END_PRECEDENCE },

    [',']               = { LEFT_ASSOCIATIVE, SEQUENCE_PRECEDENCE },

    ['=']               = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_ADD_ASSIGN]    = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_AND_ASSIGN]    = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_DIV_ASSIGN]    = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_LEFT_ASSIGN]   = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_MOD_ASSIGN]    = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_MUL_ASSIGN]    = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_OR_ASSIGN]     = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_RIGHT_ASSIGN]  = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_SUB_ASSIGN]    = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },
    [TOK_XOR_ASSIGN]    = { RIGHT_ASSOCIATIVE, ASSIGN_PRECEDENCE, true },

    ['?']               = { RIGHT_ASSOCIATIVE, CONDITIONAL_PRECEDENCE },
    [':']               = { RIGHT_ASSOCIATIVE, CONDITIONAL_PRECEDENCE },

    [TOK_OR_OP]         = { LEFT_ASSOCIATIVE, LOGICAL_OR_PRECEDENCE },

    [TOK_AND_OP]        = { LEFT_ASSOCIATIVE, LOGICAL_AND_PRECEDENCE },

    ['|']               = { LEFT_ASSOCIATIVE, OR_PRECEDENCE },

    ['^']               = { LEFT_ASSOCIATIVE, EXCLUSIVE_OR_PRECEDENCE },

    ['&']               = { LEFT_ASSOCIATIVE, AND_PRECEDENCE },

    [TOK_EQ_OP]         = { LEFT_ASSOCIATIVE, EQUALITY_PRECEDENCE },
    [TOK_NE_OP]         = { LEFT_ASSOCIATIVE, EQUALITY_PRECEDENCE },

    ['<']               = { LEFT_ASSOCIATIVE, RELATIONAL_PRECEDENCE },
    ['>']               = { LEFT_ASSOCIATIVE, RELATIONAL_PRECEDENCE },
    [TOK_LE_OP]         = { LEFT_ASSOCIATIVE, RELATIONAL_PRECEDENCE },
    [TOK_GE_OP]         = { LEFT_ASSOCIATIVE, RELATIONAL_PRECEDENCE },

    [TOK_LEFT_OP]       = { LEFT_ASSOCIATIVE, SHIFT_PRECEDENCE },
    [TOK_RIGHT_OP]      = { LEFT_ASSOCIATIVE, SHIFT_PRECEDENCE },

    ['+']               = { LEFT_ASSOCIATIVE, ADDITIVE_PRECEDENCE },
    ['-']               = { LEFT_ASSOCIATIVE, ADDITIVE_PRECEDENCE },

    ['*']               = { LEFT_ASSOCIATIVE, MULTIPLICATIVE_PRECEDENCE },
    ['/']               = { LEFT_ASSOCIATIVE, MULTIPLICATIVE_PRECEDENCE },
    ['%']               = { LEFT_ASSOCIATIVE, MULTIPLICATIVE_PRECEDENCE },
};

bool is_assignment_token(int token) {
  return token < TOK_NUM && g_assoc_prec[token].is_assignment;
}

