#include <algorithm>
#include <cassert>
#include <exception>
#include <fstream>
#include <iostream>
#include <list>
#include <map>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

using std::cerr;
using std::cin;
using std::cout;
using std::dec;
using std::exception;
using std::fstream;
using std::hash;
using std::hex;
using std::hexfloat;
using std::ios_base;
using std::istream;
using std::ostream;
using std::shared_ptr;
using std::string;
using std::stringstream;
using std::list;
using std::make_shared;
using std::map;
using std::max;
using std::move;
using std::pair;
using std::unordered_map;
using std::unordered_set;
using std::vector;
using std::wstring;
